name: Build and Archive IPA
on:
  push:
    branches:
      - main  # Replace with your main branch name
  # You can add more triggers as per your requirements, e.g., pull_request, schedule, etc.

jobs:
  build:
    runs-on: macos-latest  # macOS runner is required for building iOS apps

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod install

      - name: Build and Archive
        run: |
          xcodebuild archive -workspace kfd.xcworkspace -scheme kfd -archivePath $PWD/build/kfd.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphoneos

      - name: Create IPA
        run: |
          xcodebuild -exportArchive -archivePath $PWD/build/kfd.xcarchive -exportPath $PWD/build -exportOptionsPlist ExportOptions.plist

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: kfd-IPA
          path: $PWD/build/kfd.ipa
