name: Build and Archive IPA
on:
  push:
    branches:
      - main  # Replace with your main branch name
  # You can add more triggers as per your requirements, e.g., pull_request, schedule, etc.

jobs:
  build:
    runs-on: macos-latest  # macOS runner is required for building iOS apps

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Archive
        run: |
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild archive -"$filetype_parameter" "$file_to_build" -scheme kfd -archivePath $PWD/build/kfd.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphoneos

      - name: Create IPA
        run: |
          xcodebuild -exportArchive -archivePath $PWD/build/kfd.xcarchive -exportPath $PWD/build -exportOptionsPlist ExportOptions.plist -allowProvisioningUpdates CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO


      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: kfd-IPA
          path: $PWD/build/kfd.ipa
